---
- name: Add Kubernetes apt-key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
  retries: 3
  delay: 10
  register: result
  until: result is succeeded

- name: Add Kubernetes APT repository
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: "kubernetes"
  retries: 3
  delay: 10
  register: result
  until: result is succeeded

- name: Install kubelet
  apt:
    name: kubelet
    state: present
    update_cache: true
    cache_valid_time: 3600
  retries: 3
  delay: 10
  register: result
  until: result is succeeded

- name: Install kubeadm
  apt:
    name: kubeadm
    state: present
    update_cache: true
    cache_valid_time: 3600
  retries: 3
  delay: 10
  register: result
  until: result is succeeded
