galaxy_info:
  author: Mohammad Amin
  description: Install Docker & Docker Compose
  license: license (GPLv3)
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
