galaxy_info:
  author: Yosef Salmalian
  description: Copy generated ssh keys to target hosts
  license: license (GPLv3)
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
  galaxy_tags: []
