---
default_gateway4: 192.168.0.10
ansible_user: ubuntu

# compose config
install_docker_compose: false

# netplan config
netplan_configurations:
  ethernets:
    eth0:
      dhcp4: false
      addresses:
        - "{{ ansible_host }}/24"
      nameservers:
        addresses:
          - "{{ default_dns_addresses.0 }}"
          - "{{ default_dns_addresses.1 }}"
      gateway4: "{{ default_gateway4 }}"
      match:
        macaddress: "{{ ansible_facts['eth0']['macaddress'] }}"
      mtu: 1442
      set-name: eth0
